#!/usr/bin/env bash
# Auto-SelfControl basic command-line interface

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Check if config file already exists
if [[ -d "$HOME/.config/auto-selfcontrol/" ]]; then
    CONFIG_FILE="$HOME/.config/auto-selfcontrol/config.json"
elif [ -f "/usr/local/etc/auto-selfcontrol/config.json" ]; then
    CONFIG_FILE="/usr/local/etc/auto-selfcontrol/config.json"
elif [ -f "$DIR/config.json" ]; then
    CONFIG_FILE="$DIR/config.json"
else
    # No config file found: create it in ~/.config/auto-selfcontrol/
    mkdir -p "$HOME/.config/auto-selfcontrol/" || true
    CONFIG_FILE="$HOME/.config/auto-selfcontrol/config.json"
fi

b=$(tput bold)
n=$(tput sgr0)
HELP_TEXT="Auto-SelfControl
Small utility to schedule start and stop times of SelfControl.

Usage: ${b}$(basename "$0") <config|activate|help>${n}

where:
  ${b}config${n}    Open the schedule configuration file in a text
              editor to set up weekly parameters
  ${b}activate${n}  Activate the automatic start/stop of SelfControl
              according to schedules defined in configuration
  ${b}help${n}      Show this help message

More instructions at https://github.com/andreasgrill/auto-selfcontrol"

# Check if python3 was found
/usr/bin/python3 --version > /dev/null 2>&1
if [ "$?" -ne 0 ]; then
    >&2 echo "ERROR: Python3 was not found. Please install python3, e.g.: brew install python3"
    exit 1
fi

if [[ $1 ]]; then
    case "$1" in
        # Edit configuration file
        config|edit|set|conf*)
            # If no "config.json" found
            if [[ ! -f $CONFIG_FILE ]]; then
                curl -L -s "https://raw.githubusercontent.com/andreasgrill/auto-selfcontrol/master/config.json" -o $CONFIG_FILE
                echo "Downloaded sample configuration in $CONFIG_FILE"
            fi
            echo "Opening $CONFIG_FILE"
            # Opening with default editor set as $EDITOR
            if [[ $EDITOR ]]; then
                $EDITOR $CONFIG_FILE
            # Or with default GUI text editor (txt files > Open with...)
            else
                open -t $CONFIG_FILE
            fi
            ;;
        # Install plist config
        activate|install)
            sudo /usr/bin/python3 $DIR/auto-selfcontrol.py --install --dir "$(dirname $CONFIG_FILE)"
            exit 0
            ;;
        -h|--help|help|*)
            echo "$HELP_TEXT"
            exit 0
            ;;
    esac
else
    echo "$HELP_TEXT"
    exit 0
fi
